apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RootPass123!"
  MYSQL_DATABASE: "petclinic"
  MYSQL_USER: "petuser"
  MYSQL_PASSWORD: "PetPass456!"