apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  APPLICATION_NAME: "Spring PetClinic"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "mysql"
  SPRING_DATASOURCE_INITIALIZATION_MODE: "always"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"